[project]
name = "wegpiraten"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docxtpl>=0.20.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "pathlib>=1.0.1",
    "qrcode[pil]>=8.2",
    "rich>=14.1.0",
]
