structure:
  prj_root: /home/stephan/projects/wegpiraten
  shared_data_path: data
  output_path: output
  template_path: templates
  tmp_path: .tmp
  log_path: .logs
  local_data_path: data
  imports_path: import
  done_path: done
  graphics: graphics

database:
  sqlite_db_name: wegpiraten.sqlite3
  db_name: wegpiraten_datenbank.xlsx
  db_encrypted: true
  # db password in .env

logging:
  log_file: wegpiraten.log
  log_level: DEBUG

templates:
  invoice_template_name: rechnungsvorlage.docx
  sheet_name: Pivot Rechnungsdaten # deprecated, use sqlite table name
  # TODO: Felder des Invoice Templates noch in Config aufnehmen

  time_sheet_header_cells:
    employee_name: C5
    emp_id: F5
    reporting_month: C6
    allowed_hours_per_month: C7
    service_type: G7
    short_code: C8
    client_id: F8
  time_sheet_data_start_cell: A10
  time_sheet_data_end_cell: H28
  time_sheet_row_mapping:
    service_time: A
    service_date: B
    travel_time: C
    travel_distance: D
    direct_time: E
    indirect_time: F
    billable_hours: G # Summe aus travel_time, direct_time, indirect_time, information only
    notes: H

  time_sheet_template: time_sheet_template.xlsx
  client_sheet_name: MD_Klienten # deprecated, use sqlite table name
  # sheet password in .env

# Globale Formatierungseinstellungen für Babel/Jinja2-Filte
formatting:
  locale: de_CH
  currency: CHF
  currency_format: "#,##0.00 ¤"
  date_format: "dd.MM.yyyy"
  numeric_format: "#,##0.00"

service_provider:
  name: Wegpiraten GmbH
  street: Alpenstrasse 2
  zip_code: '3800'
  city: Interlaken
  phone: +41 (0)76 790 67 56
  email: info@wegpiraten.ch
  website: www.wegpiraten.ch
  uid: CHE-123.456.789 MWST
  bank: Bank EKI Genossenschaft
  iban: CH07 0839 3053 8385 3915 1


entities:
  employee:
    fields:
      - name: emp_id
        type: str
        primary_key: true
        excel_column: employee_id
      - name: first_name
        type: str
        excel_column: first_name
      - name: last_name
        type: str
        excel_column: last_name
      - name: fte
        type: float
        excel_column: fte
        format: ${numeric_format}
      - name: notes
        type: str
        excel_column: notes
        optional: true

  client:
    fields:
      - name: client_id
        type: str
        primary_key: true
        excel_column: client_id
      - name: social_security_number
        type: str
        excel_column: social_security_number
      - name: first_name
        type: str
        excel_column: first_name
      - name: last_name
        type: str
        excel_column: last_name
      - name: short_code
        type: str
        excel_column: short_code
      - name: payer_id
        type: str
        excel_column: payer_id
      - name: service_requester_id
        type: str
        excel_column: service_requester_id
      - name: start_date
        type: str
        excel_column: start_date
        format: ${date_format}
      - name: end_date
        type: str
        excel_column: end_date
        format: ${date_format}
        optional: true
      - name: employee_id # foreign key
        type: str
        excel_column: employee_id
      - name: travel_time
        type: float
        optional: true
        excel_column: travel_time
        format: ${numeric_format}
      - name: direct_efforts
        type: float
        optional: true
        excel_column: direct_efforts
        format: ${numeric_format}
      - name: indirect_efforts
        type: float
        optional: true
        excel_column: indirect_efforts
        format: ${numeric_format}
      - name: service_type
        type: str
        excel_column: service_type_id
      - name: notes
        type: str
        excel_column: notes
        optional: true

  payer:
    fields:
      - name: payer_id
        type: str
        primary_key: true
        excel_column: payer_id
      - name: name
        type: str
        excel_column: name
      - name: name2
        type: str
        optional: true
        excel_column: name2
      - name: street
        type: str
        excel_column: street
      - name: zip_code
        type: str
        excel_column: zip_code
      - name: city
        type: str
        excel_column: city
      - name: notes
        type: str
        excel_column: notes
        optional: true

  service_requester:
    fields:
      - name: service_requester_id
        type: str
        primary_key: true
        excel_column: service_requester_id
      - name: name
        type: str
        excel_column: name

  service_type:
    fields:
      - name: service_type_id
        type: str
        primary_key: true
        excel_column: service_type_id
      - name: code
        type: str
        excel_column: code
      - name: description
        type: str
        excel_column: description
        optional: true
      - name: hourly_rate
        type: float
        excel_column: hourly_rate
        format: ${numeric_format}
      - name: km_rate
        type: float
        excel_column: km_rate
        format: ${numeric_format}
      - name: rundung
        type: float
        excel_column: rundung
        format: ${numeric_format}
      - name: from_date
        type: str
        excel_column: from_date
        format: ${date_format}
        optional: true
      - name: notes
        type: str
        excel_column: notes
        optional: true

  invoice_data:
    fields:
      - name: invoice_number
        type: str
        primary_key: true
        excel_column: Rechnungs-Nr
      - name: client_id
        type: str
        excel_column: Klient-Nr.
      - name: service_time
        type: str
        excel_column: Uhrzeit
        format: ${date_format} - ${date_format}
      - name: service_date
        type: str
        excel_column: Leistungsdatum
        format: ${date_format}
        is_position: true
      - name: service_type
        type: str
        excel_column: Betreuungstyp
      - name: travel_time
        type: float
        excel_column: Fahrtzeit
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: direct_time
        type: float
        excel_column: Direkt
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: indirect_time
        type: float
        excel_column: Indirekt
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      # - name: billable_hours
      #   type: float
      #   excel_column: Sollstunden
      #   format: ${numeric_format}
      #   decimals: 2
      #   is_position: true
      #   sum: true
      # - name: hourly_rate
      #   type: currency
      #   excel_column: Stundensatz
      #   format: ${currency_format}
      #   decimals: 2
      #   is_position: false
      #   sum: false
      # - name: km_allowance
      #   type: float
      #   excel_column: km_Pauschale
      #   format: ${numeric_format}
      #   decimals: 2
      #   is_position: false
      #   sum: true
      #   optional: true
      # - name: total_hours
      #   type: float
      #   excel_column: Stunden
      #   format: ${numeric_format}
      #   decimals: 2
      #   is_position: true
      #   sum: true
      # - name: total_costs
      #   type: currency
      #   excel_column: Kosten
      #   format: ${currency_format}
      #   is_position: true
      #   sum: true
      - name: service_requester_name
        type: str
        excel_column: Leistungsbesteller
      - name: payer_id
        type: str
        excel_column: ZDNR

# TODO: löschen nach import
table_mappings:
  masterdata_employee:
    entity: employee
    target: employees
  masterdata_service_requester:
    entity: service_requester
    target: service_requester
  masterdata_payer:
    entity: payer
    target: payer
  masterdata_client:
    entity: client
    target: clients
  invoice_data:
    entity: invoice_data
    target: invoice_data
