structure:
  prj_root: /home/stephan/projects/wegpiraten
  shared_data_path: /mnt/c/Users/micro/OneDrive/Shared/Beatus/Wegpiraten Unterlagen
  output_path: output
  template_path: templates
  tmp_path: .tmp
  log_path: .logs
  local_data_path: data
  graphics: graphics

database:
  sqlite_db_name: Wegpiraten Datenbank.sqlite3
  db_name: Wegpiraten Datenbank.xlsx
  db_encrypted: true
  # db password in .env

logging:
  log_file: wegpiraten.log
  log_level: DEBUG

templates:
  invoice_template_name: rechnungsvorlage.docx
  sheet_name: Pivot Rechnungsdaten # deprecated, use sqlite table name

  reporting_template: zeiterfassungsboegen.xlsx
  client_sheet_name: MD_Klienten # deprecated, use sqlite table name
  # sheet password in .env

# Globale Formatierungseinstellungen für Babel/Jinja2-Filte
formatting:
  locale: de_CH
  currency: CHF
  currency_format: "#,##0.00 ¤"
  date_format: "dd.MM.yyyy"
  numeric_format: "#,##0.00"

service_provider:
  name: Wegpiraten GmbH
  street: Alpenstrasse 2
  zip_code: '3800'
  city: Interlaken
  phone: +41 (0)76 790 67 56
  email: info@wegpiraten.ch
  website: www.wegpiraten.ch
  uid: CHE-123.456.789 MWST
  bank: Bank EKI Genossenschaft
  iban: CH07 0839 3053 8385 3915 1


models:
  employee:
    fields:
      - name: emp_id
        type: str
        primary_key: true
        excel_column: PersNr
      - name: first_name
        type: str
        excel_column: Vorname
      - name: last_name
        type: str
        excel_column: Nachname
      - name: fte
        type: float
        excel_column: FTE
        format: ${numeric_format}
      - name: notes
        type: str
        excel_column: Kommentar
        optional: true

  client:
    fields:
      - name: client_id
        type: str
        primary_key: true
        excel_column: KlientNr
      - name: social_security_number
        type: str
        excel_column: SozVersNr
      - name: first_name
        type: str
        excel_column: Vorname
      - name: last_name
        type: str
        excel_column: Nachname
      - name: short_code
        type: str
        excel_column: Kürzel
      - name: payer_id
        type: str
        excel_column: ZdNr
      - name: service_requester_id
        type: str
        excel_column: LbNr
      - name: start_date
        type: str
        excel_column: Beginn
        format: ${date_format}
      - name: end_date
        type: str
        excel_column: Ende
        format: ${date_format}
        optional: true
      - name: employee_id # foreign key
        type: str
        excel_column: MA_ID
      - name: allowed_hours_per_month
        type: float
        optional: true
        excel_column: Stunden pro Monat
        format: ${numeric_format}
        sum: true
      - name: service_type
        type: str
        excel_column: SPF / BBT
      - name: notes
        type: str
        excel_column: Kommentar
        optional: true

  payer:
    fields:
      - name: payer_id
        type: str
        primary_key: true
        excel_column: ZdNr
      - name: name
        type: str
        excel_column: ZD_Name
      - name: name2
        type: str
        optional: true
        excel_column: ZD_Name2
      - name: street
        type: str
        excel_column: ZD_Strasse
      - name: zip_code
        type: str
        excel_column: ZD_PLZ
      - name: city
        type: str
        excel_column: ZD_Ort
      - name: notes
        type: str
        excel_column: Kommentar
        optional: true

  service_requester:
    fields:
      - name: service_requester_id
        type: str
        primary_key: true
        excel_column: LBNr
      - name: name
        type: str
        excel_column: Leistungsbesteller

  invoice_data:
    fields:
      - name: invoice_number
        type: str
        primary_key: true
        excel_column: Rechnungs-Nr
      - name: client_id
        type: str
        excel_column: Klient-Nr.
      - name: service_date
        type: str
        excel_column: Leistungsdatum
        format: ${date_format}
        is_position: true
      - name: service_type
        type: str
        excel_column: Betreuungstyp
      - name: travel_time
        type: float
        excel_column: Fahrtzeit
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: direct_time
        type: float
        excel_column: Direkt
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: indirect_time
        type: float
        excel_column: Indirekt
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: billable_hours
        type: float
        excel_column: Sollstunden
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: hourly_rate
        type: currency
        excel_column: Stundensatz
        format: ${currency_format}
        decimals: 2
        is_position: false
        sum: false
      # - name: km_allowance
      #   type: float
      #   excel_column: km_Pauschale
      #   format: ${numeric_format}
      #   decimals: 2
      #   is_position: false
      #   sum: true
      #   optional: true
      - name: total_hours
        type: float
        excel_column: Stunden
        format: ${numeric_format}
        decimals: 2
        is_position: true
        sum: true
      - name: total_costs
        type: currency
        excel_column: Kosten
        format: ${currency_format}
        is_position: true
        sum: true
      - name: service_requester_name
        type: str
        excel_column: Leistungsbesteller
      - name: payer_id
        type: str
        excel_column: ZDNR

# TODO: löschen nach import
table_mappings:
  MD_MA:
    entity: employee
    target: employees
  Leistungsbesteller:
    entity: service_requester
    target: service_requester
  Zahlungsdienstleister:
    entity: payer
    target: payer
  MD_Client:
    entity: client
    target: clients
  invoice_data:
    entity: invoice_data
    target: invoice_data
