prj_root: /home/stephan/projects/wegpiraten
data_path: /mnt/c/Users/micro/OneDrive/Shared/Beatus/Wegpiraten Unterlagen
output_path: output
template_path: vorlagen
invoice_template_name: rechnungsvorlage.docx
db_name: Wegpiraten Datenbank.xlsx
sheet_name: Pivot Rechnungsdaten