structure:
  prj_root: /home/stephan/projects/wegpiraten
  shared_data_path: /mnt/c/Users/micro/OneDrive/Shared/Beatus/Wegpiraten Unterlagen
  output_path: output
  template_path: templates
  tmp_path: .tmp
  log_path: .logs
  local_data_path: data

sqlite_db_name: Wegpiraten Datenbank.sqlite3
db_name: Wegpiraten Datenbank.xlsx
db_encrypted: true
# db password in .env


log_file: wegpiraten.log
log_level: DEBUG

invoice_template_name: rechnungsvorlage.docx
sheet_name: Pivot Rechnungsdaten

reporting_template: zeiterfassungsboegen.xlsx
client_sheet_name: MD_Klienten
# sheet password in .env

# Globale Formatierungseinstellungen für Babel/Jinja2-Filter
locale: de_CH
currency: CHF
currency_format: "#,##0.00 ¤"      # Babel: ¤ steht für das Währungssymbol
date_format: "dd.MM.yyyy"         # Babel: z.B. "yyyy-MM-dd" für ISO
numeric_format: "#,##0.00"        # Standard für numerische Felder

expected_columns:
  payer:
    - name: ZDNR
      type: text
    - name: ZD_Name
      type: text
    - name: ZD_Name2
      type: text
    - name: ZD_Strasse
      type: text
    - name: ZD_PLZ
      type: text
    - name: ZD_Ort
      type: text
  client:
    - name: Klient-Nr.
      type: text
    - name: CL_Vorname
      type: text
    - name: CL_Nachname
      type: text
    - name: CL_SozVersNr
      type: text
  general:
    - name: Leistungsbesteller
      type: text
  
    - name: Leistungsdatum
      type: date
      format: "dd.MM.yyyy"
      is_position: true           # NEU: Soll als Rechnungsposition erscheinen
      sum: false                  # NEU: Keine Summe berechnen
  
    - name: Betreuungstyp
      type: text
      is_position: false
      sum: false

    - name: Fahrtzeit
      type: numeric
      decimals: 2
      is_position: true
      sum: true                   # NEU: Summe berechnen

    - name: Direkt
      type: numeric
      decimals: 2
      is_position: true
      sum: true

    - name: Indirekt
      type: numeric
      decimals: 2
      is_position: true
      sum: true

    - name: Sollstunden
      type: numeric
      decimals: 2
      is_position: true
      sum: true

    - name: Stundensatz
      type: currency
      decimals: 2
      is_position: false
      sum: false

    - name: km_Pauschale
      type: numeric
      decimals: 2
      is_position: false
      sum: true

    - name: Stunden
      type: numeric
      decimals: 2
      is_position: true
      sum: true
 
    - name: Kosten
      type: currency
      is_position: true
      sum: true

provider:
  IBAN: CH07 0839 3053 8385 3915 1
  name: Wegpiraten GmbH
  strasse: Alpenstraße 2
  plz_ort: 3800 Interlaken

field_mappings:
  employee:
    PersNr: { field: emp_id, type: str }
    Vorname: { field: first_name, type: str }
    Nachname: { field: last_name, type: str }
    FTE: { field: fte, type: float }
    Kommentar: { field: notes, type: str }
  client:
    KlientNr: { field: client_id, type: str }
    SozVersNr: { field: social_security_number, type: str }
    Vorname: { field: first_name, type: str }
    Nachname: { field: surname, type: str }
    Kürzel: { field: short_code, type: str }
    ZdNr: { field: payer_id, type: str }
    LbNr: { field: service_requester_id, type: str }
    Beginn: { field: start_date, type: str }
    Ende: { field: end_date, type: str }
    MA_ID: { field: employee_id, type: str }
    Stunden pro Monat: { field: allowed_hours_per_month, type: float }
    SPF / BBT: { field: service_type, type: str }
    Kommentar: { field: notes, type: str }
  payer:
    ZdNr: { field: payer_id, type: str }
    ZD_Name: { field: name, type: str }
    ZD_Name2: { field: name2, type: str }
    ZD_Strasse: { field: street, type: str }
    ZD_PLZ: { field: zip_code, type: str }
    ZD_Ort: { field: city, type: str }
    Kommentar: { field: notes, type: str }
  service_requester:
    LBNr: { field: sr_key, type: str }
    Leistungsbesteller: { field: name, type: str }


table_mappings:
  MD_MA: # Excel-Tabellenname
    entity: employee # Entität im Code
    target: employees # Zieltabelle in der DB
    primary_key: emp_id # Primärschlüssel der Zieltabelle
  Leistungsbesteller:
    entity: service_requester
    target: service_requester
    primary_key: sr_key
  Zahlungsdienstleister:
    entity: payer
    target: payer
    primary_key: payer_id
  MD_Client:
    entity: client
    target: clients
    primary_key: client_id