structure:
  prj_root: /home/stephan/projects/wegpiraten
  data_path: /mnt/c/Users/micro/OneDrive/Shared/Beatus/Wegpiraten Unterlagen
  output_path: output
  template_path: templates
  tmp_path: .tmp
  logs: .logs

db_name: Wegpiraten Datenbank.xlsx

invoice_template_name: rechnungsvorlage.docx
sheet_name: Pivot Rechnungsdaten
client_sheet_name: MD_Klienten
reporting_template: zeiterfassungsboegen.xlsx

# Globale Formatierungseinstellungen für Babel/Jinja2-Filter
locale: de_CH
currency: CHF
currency_format: "#,##0.00 ¤"      # Babel: ¤ steht für das Währungssymbol
date_format: "dd.MM.yyyy"         # Babel: z.B. "yyyy-MM-dd" für ISO
numeric_format: "#,##0.00"        # Standard für numerische Felder

expected_columns:
  payer:
    - name: ZDNR
      type: text
    - name: ZD_Name
      type: text
    - name: ZD_Name2
      type: text
    - name: ZD_Strasse
      type: text
    - name: ZD_PLZ
      type: text
    - name: ZD_Ort
      type: text
  client:
    - name: Klient-Nr.
      type: text
    - name: CL_Vorname
      type: text
    - name: CL_Nachname
      type: text
    - name: CL_SozVersNr
      type: text
  general:
    - name: Leistungsbesteller
      type: text
  
    - name: Leistungsdatum
      type: date
      format: "dd.MM.yyyy"
      is_position: true           # NEU: Soll als Rechnungsposition erscheinen
      sum: false                  # NEU: Keine Summe berechnen
  
    - name: Betreuungstyp
      type: text
      is_position: false
      sum: false

    - name: Fahrtzeit
      type: numeric
      decimals: 2
      is_position: true
      sum: true                   # NEU: Summe berechnen

    - name: Direkt
      type: numeric
      decimals: 2
      is_position: true
      sum: true

    - name: Indirekt
      type: numeric
      decimals: 2
      is_position: true
      sum: true

    - name: Sollstunden
      type: numeric
      decimals: 2
      is_position: true
      sum: true

    - name: Stundensatz
      type: currency
      decimals: 2
      is_position: false
      sum: false

    - name: km_Pauschale
      type: numeric
      decimals: 2
      is_position: false
      sum: true

    - name: Stunden
      type: numeric
      decimals: 2
      is_position: true
      sum: true
 
    - name: Kosten
      type: currency
      is_position: true
      sum: true

provider:
  IBAN: CH07 0839 3053 8385 3915 1
  name: Wegpiraten GmbH
  strasse: Alpenstraße 2
  plz_ort: 3800 Interlaken