structure:
  prj_root: /home/stephan/projects/wegpiraten
  data_path: /mnt/c/Users/micro/OneDrive/Shared/Beatus/Wegpiraten Unterlagen
  output_path: output
  template_path: templates
  tmp_path: .tmp
  logs: .logs
invoice_template_name: rechnungsvorlage.docx
db_name: Wegpiraten Datenbank.xlsx
sheet_name: Pivot Rechnungsdaten
locale: de_CH.UTF-8
expected_columns:
  payer:
    - name: ZDNR
      type: text
    - name: ZD_Name
      type: text
    - name: ZD_Name2
      type: text
    - name: ZD_Strasse
      type: text
    - name: ZD_PLZ
      type: text
    - name: ZD_Ort
      type: text
  client:
    - name: Klient-Nr.
      type: text
    - name: CL_Vorname
      type: text
    - name: CL_Nachname
      type: text
    - name: CL_SozVersNr
      type: text
  general:
    - name: Leistungsbesteller
      type: text
    - name: Leistungsdatum
      type: date
      format: "%d.%m.%Y"
      position: true
    - name: Betreuungstyp
      type: text
    - name: Fahrtzeit
      type: numeric
      decimals: 2
    - name: Direkt
      type: numeric
      decimals: 2
      position: true
    - name: Indirekt
      type: numeric
      decimals: 2
      position: true
    - name: Sollstunden
      type: numeric
      decimals: 2
      position: true
    - name: Stundensatz
      type: currency
      currency: CHF
      decimals: 2
      position: true
    - name: km_Pauschale
      type: numeric
      decimals: 2
      position: true
    - name: Stunden
      type: numeric
      decimals: 2
      position: true
    - name: Kosten
      type: currency
      currency: CHF
      decimals: 2
      position: true

provider:
  IBAN: CH07 0839 3053 8385 3915 1
  name: Wegpiraten GmbH
  strasse: Alpenstraße 2
  plz_ort: 3800 Interlaken